### ISSUE TITLE
Cannot access "My Files" when username contains '@'

### ISSUE THREAD

**Issue by sebvdk** [Alfresco/alfresco-android-app#289]
Hi,
I have a issue when the user wants to access the "My Files" shortcut when username contains '@'
A popup authentication error appear and no content is displayed.

```java
org.apache.chemistry.opencmis.commons.exceptions.CmisRuntimeException: 07074087852 SOLR side error: org.apache.lucene.queryParser.ParseException: Failed to parse XPath...
    Unexpected '@'
```
This bug is resolved on iOS but not yet on Android.

This issue is referred on the Alfresco Issues portal : 
https://issues.alfresco.com/jira/browse/MOBILE-2963

The Android SDK must use CMIS instead of REST.

Thank you for your precious help.

**Comment by jmpascal** [comment]
Hello,

The resolution of this bug will be in the next release of Alfresco Android  Application.

**Comment by sebvdk** [comment]
Hello,
Thank you for your quick reply.
I will wait for the next release.
