### ISSUE TITLE
Could not find org.alfresco.mobile.android.sdk:alfresco-mobile-android-client-api:1.4.0.

### ISSUE THREAD

**Issue by mahermeg17** [Alfresco/alfresco-android-app#306]
Hi

I have an error while compiling the project with android studio and it's the same when compilling with commande line.

android studio message : 
Error:(44, 13) Failed to resolve: org.alfresco.mobile.android.sdk:alfresco-mobile-android-client-api:1.4.0
Error:(28, 13) Failed to resolve: com.samsung.android:sdk:1.0.0
Error:(27, 13) Failed to resolve: com.samsung.android.sdk:pen:1.0.2

This is the log for CLI when running sudo ./gradlew assembleCustomRelease

....................
Download https://jcenter.bintray.com/com/squareup/okhttp/okhttp/1.5.2/okhttp-1.5.2.jar
Download https://jcenter.bintray.com/com/mattprecious/telescope/telescope/1.3.0/telescope-1.3.0.aar
Download https://jcenter.bintray.com/com/jmpergar/AwesomeText/1.0.0/AwesomeText-1.0.0.aar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':alfresco-mobile-android'.
> A problem occurred configuring project ':platform:foundation'.
   > Could not resolve all dependencies for configuration ':platform:foundation:_releaseCompile'.
      > Could not find org.alfresco.mobile.android.sdk:alfresco-mobile-android-client-api:1.4.0.
        Searched in the following locations:
            file:/root/.m2/repository/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.pom
            file:/root/.m2/repository/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.jar
            https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.pom
            https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.jar
            https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.pom
            https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.jar
            https://jcenter.bintray.com/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.pom
            https://jcenter.bintray.com/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.jar
            https://repo1.maven.org/maven2/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.pom
            https://repo1.maven.org/maven2/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.jar
            file:/media/maher/workspace/adt-bundle-linux-x86_64-20140702/sdk/extras/android/m2repository/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.pom
            file:/media/maher/workspace/adt-bundle-linux-x86_64-20140702/sdk/extras/android/m2repository/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.jar
            file:/media/maher/workspace/adt-bundle-linux-x86_64-20140702/sdk/extras/google/m2repository/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.pom
            file:/media/maher/workspace/adt-bundle-linux-x86_64-20140702/sdk/extras/google/m2repository/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.jar
        Required by:
            alfresco-android-app-master.platform:foundation:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4 mins 35.026 secs

**Comment by jmpascal** [comment]
Hello,

Alfresco Mobile 1.5 has not been released yet. 
This version is based on Alfresco Android SDK 1.4 which is also not been released for the moment. 

To build master branch you need to build master Android SDK master branch before building App master branch at https://github.com/Alfresco/alfresco-android-sdk

It explains why you have this missing artifacts issue.

**Comment by jmpascal** [comment]
We released yesterday our application & sdk so you will be able to retrieve the dependencies from our maven repository.

**Comment by kachaj7** [comment]
Why this ticket is clodes? The project https://github.com/Alfresco/alfresco-android-sdk it's impossible to compile.

[ERROR] Failed to execute goal on project alfresco-mobile-android-client-api: Co
uld not resolve dependencies for project org.alfresco.mobile.android.sdk:alfresc
o-mobile-android-client-api:jar:1.4.0: Failed to collect dependencies for [com.g
oogle.android:android:jar:4.1.1.4 (provided), com.google.android:annotations:jar
:4.1.1.4 (provided), org.apache.chemistry.opencmis:chemistry-opencmis-android-cl
ient:jar:0.11.0 (compile), org.slf4j:slf4j-android:jar:1.6.1-RC1 (compile), org.
alfresco.cmis.client:alfresco-opencmis-extension:jar:0.7-ANDROID (compile)]: Fai
led to read artifact descriptor for org.alfresco.cmis.client:alfresco-opencmis-e
xtension:jar:0.7-ANDROID: Failure to transfer org.alfresco.cmis.client:alfresco-
opencmis-extension:pom:0.7-ANDROID from https://artifacts.alfresco.com/nexus/con
tent/repositories/releases was cached in the local repository, resolution will n
ot be reattempted until the update interval of artifacts.alfresco.com has elapse
d or updates are forced. Original error: Could not transfer artifact org.alfresc
o.cmis.client:alfresco-opencmis-extension:pom:0.7-ANDROID from/to artifacts.alfr
esco.com (https://artifacts.alfresco.com/nexus/content/repositories/releases): j
ava.lang.RuntimeException: Could not generate DH keypair -> [Help 1]

**Comment by jmpascal** [comment]
Hello,

This ticket has been closed because artifacts has been released which was the original issue here (missing artifacts).

Regarding your issue apparently the root cause is  **Could not generate DH keypair**
After googling a bit it appears it's a known issue on JDK level.
Do you use a JDK version ?
Which version is it ?
What's your maven version ?
Have you try to test with another JDK ?

The best workaround for you is to eventually get your missing artifacts here :
* https://artifacts.alfresco.com/nexus/content/repositories/releases/org/alfresco/cmis/client/alfresco-opencmis-extension/0.7-ANDROID/
* Or if building the SDK is not mandatory, you can download [the latest jar file][2] or [the latest Zip file][1] (client-api + dependencies)

[1]:https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.0/alfresco-mobile-android-client-api-1.4.0.jar
[2]: http://dl.alfresco.com/release/mobile/androidsdk-1.4.0/alfresco-android-sdk-1.4.0.zip

**Comment by kachaj7** [comment]
Thanks, for the fast reply. I have updated jdk to 8 and maven to version 3.3.2. After disabling some tests I have compiled everything but no samsung artifacts have been downloaded. 

On Android Studio start I get
Error:Failed to find: com.samsung.android:sdk:1.0.0
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>

Error:Failed to find: com.samsung.android.sdk:pen:1.0.2
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>

Will the above files fix the problem?

**Comment by jmpascal** [comment]
We are not allowed to redistribute Samsung SDK Librairies.
To include them you need to go to Samsung Mobile Developer Web Site and get them here.

I would also recommend inside your Android Studio to use the tutorial defined in the wiki https://github.com/Alfresco/alfresco-android-app/wiki/Getting-Started#build-the-application

Have a focus particularly on **Build Variants View** and use **customRelease**
With this build type you don't need Samsung depedencies and the app will work without it.

**Comment by cybermakoki** [comment]
Hi, I've tried to build the app with customRelease and I still have the issue with samsung libraries

**Comment by jmpascal** [comment]
To solve this issue You can also comment              
```
storeCompile project(':extensions:samsung')
```
in **alfresco-android-app\gradle.properties**

**Comment by cybermakoki** [comment]
Thanks for your quick reply jmpascal, 
I've found that line in alfresco-mobile-android/build.gradle and still doesn't work :(

**Comment by jmpascal** [comment]
Do you build with Android Studio or command line ?

**Comment by cybermakoki** [comment]
I'm with Android Studio

**Comment by jmpascal** [comment]
After commenting clean & rebuild your project.

If it doesn't solve the issue you still can comment 
```
include ':extensions:samsung'
```
in **settings.gradle**

**Comment by cybermakoki** [comment]
I tried that but then I get this error:

Project 'samsung' not found in project ':extensions'

**Comment by jmpascal** [comment]
if you  comment              
```
storeCompile project(':extensions:samsung')
```
in **alfresco-android-app\gradle.properties**

and comment 
```
include ':extensions:samsung'
```
in **settings.gradle**

And after that **Rebuild/clean Project and/or Sync Project with Gradle Files** the project shouldn't integrate the Samsung module at all.

**Comment by cybermakoki** [comment]
Thanks jmpascal, it works now, I just reopen the studio an clean/rebuild the project.

Maybe you could add this workaround to the wiki, I think it's useful.

Thanks!
