### ISSUE TITLE
JBPM Workflows

### ISSUE THREAD

**Issue by patriciay-appno** [Alfresco/alfresco-android-app#336]
Hi, 
I would like to add new custom workflows to the app, is this possible? is it compatible with JBPM?

thanks

**Comment by jmpascal** [comment]
Aloah.

Sorry for the delay. (Holidays)

By default inside the application no it's not possible. We only support default Alfresco Workflow (Activiti or JBPM)

However it's "possible" to create a custom version of the application to add custom workflow support. 
It requires quite a lot of new code to integrate.

We currently focus on Activiti client like https://play.google.com/store/apps/details?id=com.activiti.android.app
