### ISSUE TITLE
Preview doesn't generate the image

### ISSUE THREAD

**Issue by iwkse** [Alfresco/alfresco-android-app#345]
Hi,
I've just noticed that from the app it seems it only search for the thumbnail available to preview but doesn't do any transform.
To reproduce that, I've selected an image from the app which doesn't show a preview, getting a preview not available, after this went from the web client to the same image, open to preview and after that the preview is available on the app as well.

**Comment by jmpascal** [comment]
Aloah,

Sadly it's a limitation from our REST API and server.
It's not possible from a Client (like Android) to request the creation of a large preview.
