### ISSUE TITLE
Favourite menu : scrolling don't work

### ISSUE THREAD

**Issue by mlenormand** [Alfresco/alfresco-android-app#361]
Steps to reproduce the problem : 

1) In Alfresco Share, set as favourite a folder with 20+ documents/subfolders
2) In the Alfresco Android app, go to the "Favourite" menu
3) Wait for the folder to be synchronized with the Alfresco Android app
4) When the folder shows up in the list, go into it
5) Try to scroll the list to view the next documents/subfolders
On each scroll, the list comes back to the top, i.e. the scrolling is not possible and the next items can't be accessed.

This behaviour is not always reproductible, maybe it occurs only when the sync process is active ?

Reproduced with Alfresco Android app 1.5.2 connected with a Alfresco Share v4.2.0.

This issue is blocking because it prevents the users to use the offline mode (synchronized folders contain 100+ subfolders).

This issue has been also published in the JIRA.

**Comment by mikeh** [comment]
Thanks for the bug report. I couldn't find the issue in JIRA, could you attach the ticket reference please?

Note that we are (quite literally) just about to release version 1.6 of the Android App. It should be available via the Play Store in the next day or so, so I would be interested to hear if the problem persists with that version. If it does, we'll follow up with requesting more information such as the Android version / device type / etc - but let's wait until you test with v1.6.

Thanks,
Mike

**Comment by mikeh** [comment]
JIRA issue: https://issues.alfresco.com/jira/browse/MOBILE-3382

**Comment by mlenormand** [comment]
OK, thank you for your reactity.
The JIRA issue : https://issues.alfresco.com/jira/browse/MOBILE-3382

**Comment by jmpascal** [comment]
Aloah.

Is it still valid with 1.6 ?

Thanks in advance.
