### ISSUE TITLE
Trying to compile 1.6 version with Gradle

### ISSUE THREAD

**Issue by wojtekjablonski96** [Alfresco/alfresco-android-app#363]
Hi, I'm trying to compile the latest version of the app and I get this error with gradle from terminal (Mac). 
The error refers to the Alfresco SDK 1.4.1

compile 'org.alfresco.mobile.android.sdk:alfresco-mobile-android-client-api:1.4.1'

 FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':alfresco-mobile-android'.
> A problem occurred configuring project ':mdm:mobileiron'.
   > A problem occurred configuring project ':platform:foundation'.
      > Could not resolve all dependencies for configuration ':platform:foundation:_debugCompile'.
         > Could not find org.alfresco.mobile.android.sdk:alfresco-mobile-android-client-api:1.4.1.
           Searched in the following locations:
               file:/Users/wojtekjablonski/.m2/repository/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.pom
               file:/Users/wojtekjablonski/.m2/repository/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.jar
               https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.pom
               https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.jar
               https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.pom
               https://artifacts.alfresco.com/nexus/content/groups/public-snapshots/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.jar
               https://jitpack.io/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.pom
               https://jitpack.io/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.jar
               https://jcenter.bintray.com/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.pom
               https://jcenter.bintray.com/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.jar
               https://repo1.maven.org/maven2/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.pom
               https://repo1.maven.org/maven2/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.jar
               file:/Users/wojtekjablonski/Library/Android/sdk/extras/android/m2repository/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.pom
               file:/Users/wojtekjablonski/Library/Android/sdk/extras/android/m2repository/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.jar
               file:/Users/wojtekjablonski/Library/Android/sdk/extras/google/m2repository/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.pom
               file:/Users/wojtekjablonski/Library/Android/sdk/extras/google/m2repository/org/alfresco/mobile/android/sdk/alfresco-mobile-android-client-api/1.4.1/alfresco-mobile-android-client-api-1.4.1.jar
           Required by:
               alfresco-android-app-1.6.platform:foundation:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 43.623 secs
DESKTOP-4I1Q6EF:alfresco-android-app-1.6 wojtekjablonski$

**Comment by jmpascal** [comment]
Aloah,

Sorry for the late response (I didn't receive the notification when you created the issue originally) but yes it happened the SDK wasn't available at those time. We often release the APP version before the SDK version which creates this issue.

Thanks for sharing this information and hope everything works fine now.
