### ISSUE TITLE
Failed to resolve: com.afollestad:material-dialogs:0.7.6.0

### ISSUE THREAD

**Issue by astrachan** [Alfresco/alfresco-android-app#364]
During building 1.6 the following problem in resolving dependencies is seen:

Error:Failed to resolve: com.afollestad:material-dialogs:0.7.6.0

Adding the following repository to build.gradle might overcome it:

maven { 
  url "https://jitpack.io" 
}

**Comment by jmpascal** [comment]
Added for 1.6.1

Thanks.
