### ISSUE TITLE
Search fails for some strings

### ISSUE THREAD

**Issue by iwkse** [Alfresco/alfresco-android-app#365]
Hi, I'm experiencing this problem, if I search something that is actually available it works fine. When instead the content is not found, for some strings it fails and it's weird.

I've tried with team or login

We've reproduced it on our server, does anyone can test this?

Thanks

**Comment by jmpascal** [comment]
Aloah,

Can you be more precise on your description of "fail" ? Does the app crashes or the UI displays something wrong ?
What version of the app do you use ? Is it build from source code or is it the play store version ?
Can you share a screenshot ?

Thanks in advance.

**Comment by iwkse** [comment]
heya,

what really happens is that searching for such terms I specified, I get a red error message message saying I don't have access to get such resource. There's no crash, only this red message. The version is the current git, I've built it from there.

HTH,
let me know

**Comment by jmpascal** [comment]
Could you update to the latest 1.6.1 and see if this issue is still present.

Thanks in advancE.

**Comment by iwkse** [comment]
Thanks, as soon as I can try this I will let you know

Thanks

**Comment by jmpascal** [comment]
Without news I will close this issue. Don't hesitate to open a new one or comment on this one.
Thanks.
