### ISSUE TITLE
Malformed User-Agent

### ISSUE THREAD

**Issue by lelmarir** [Alfresco/alfresco-android-app#375]
The android app reports itself (User-Agent) as "Apache Chemistry OpenCMIS/0.0"

Thi user agent is Wrong and Incomplete. It should,at least be, "ApacheChemistryOpenCMIS/0.0" (without spaces), and maybe report the correct version instead of 0.0

But it could also specify the application, not only the used protocol: "ApacheChemistryOpenCMIS/0.0 alfresco-android-app/1.6" 

(this way i can configure my server to allow the application and block anything else. Not bulletproof, but at least...)

> The User-Agent request-header field contains information about the user agent originating the request. This is for statistical purposes, the tracing of protocol violations, and automated recognition of user agents for the sake of tailoring responses to avoid particular user agent limitations. User agents SHOULD include this field with requests. The field can contain multiple product tokens (section 3.8) and comments identifying the agent and any subproducts which form a significant part of the user agent. By convention, the product tokens are listed in order of their significance for identifying the application.
> 
> >   User-Agent     = "User-Agent" ":" 1*( product | comment )
> 
> Where product is defined as:
> 
> >    product         = token ["/" product-version]
> >    product-version = token
> >    token           = 1*<any CHAR except CTLs or separators>
> 
> And comment as:
> 
> >   comment        = "(" *( ctext | quoted-pair | comment ) ")"
> >   ctext          = <any TEXT excluding "(" and ")">

**Comment by jmpascal** [comment]
Hello,

Sorry for the long delay for this issue. This part is managed by our SDK layer and we didn't plan to update it in 2016. The next App version of the app will include a new version so we will try to update the User Agent.

From your perspective what would be the best user agent for the APP ?

Thanks in advance.

**Comment by lelmarir** [comment]
Hi,

as stated before, the best user agent would be "ApacheChemistryOpenCMIS/0.0 alfresco-android-app/1.6" (using the correct version of ApacheChemistryOpenCMIS instead of 0.0) IMO.

**Comment by shikoko** [comment]
Closing this issue since it was opened in 2016, please reopen and comment if you need further assistance.
