### ISSUE TITLE
Calendar support

### ISSUE THREAD

**Issue by iwkse** [Alfresco/alfresco-android-app#387]
Hi,
this is more like an improvement than a bug. Right now the app does not support the calendar, to insert/view events.

Is this planned to be developed in the future?

Thanks

**Comment by jmpascal** [comment]
Aloah,

In short term we don't plan to support this feature as there's no consistent API available across all Alfresco version we support. Nevertheless with the development of new APIs in 5.2 time frame there's a chance we could integrate it and support it in Alfresco 5.2+ but can't guarantee it at 100%

**Comment by iwkse** [comment]
Hi, I had a hint it was something like that..thanks for your explanation

Best regards
