### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [Alfresco/alfresco-android-app#389]
Would you consider publishing the `.apk` here on Github, preferably attaching it to the corresponding release on the `releases/` page? That way it would be easily available to those "Google resisters" running "Google free devices" (i.e. without the GApps and thus without Play Store). Placing it on the `releases/` page (with the tag corresponding to the version), I could even grab updates automatically and put them [here](https://android.izzysoft.de/repo), permitting users to auto-update using the F-Droid app.

**Comment by jmpascal** [comment]
Hello,

First of all Thank you for your question.
We don't publish the APK in Github as we want a single way to publish and distribute our application. And the best way for us is the Google Play Store. If any Alfresco customer wants to get the APK by bypassing Google Play distribution it's possible to contact Alfresco Support or contacting by email mobile AT alfresco dot com.

Hope it helps.

**Comment by IzzySoft** [comment]
Thanks for the clear answer! Not what I had hoped for, but of course I accept your decision.

The group of people chosing to use their Android devices w/o GApps (mostly for privacy reasons – but also for the reason those are often a resource hog) seems to be growing. Not everybody will directly approach the developer for the `.apk`, some just go for "other alternatives" when they don't find it.  Moreover: if one has to manually install the `.apk`, there won't be "automatic updates" or at least "update reminders".

So in case you change your mind one day, please let me know :)
