### ISSUE TITLE
The configuration.json don´t work

### ISSUE THREAD

**Issue by robsoncardosoti** [Alfresco/alfresco-android-app#405]
I created the configuration.json in the folder Data Dictionary/Mobile, but in the Alfresco mobile the menus don´t are oculted.
I tested using the steps of http://docs.alfresco.com/5.1/concepts/mobile-config-overview.html.
My configuration.json is attachhed

[configuration.json.txt.txt](https://github.com/Alfresco/alfresco-android-app/files/540504/configuration.json.txt.txt)

The configuration.json is copied to local folder Android/data/org.alfresco.mobile.android.application/files/hostnameserver-username/Config in my mobile, but the Alfresco mobile only read the Android/data/org.alfresco.mobile.android.application/files/hostnameserver-username/Custom Folder.

**Comment by jmpascal** [comment]
Hello,

Could you confirm this behaviour is still present with the latest version of Alfresco Mobile available in the Play store.
The rules here is the configuration embedded in the app can be overwritten by the on defined by the user in settings which can be overwritten by the one provided by the server. So at the end the server configuration always wins.

Thanks in advance.

**Comment by robsoncardosoti** [comment]
I already solved the problem by configuring the files on the server.
