### ISSUE TITLE
The View File Properties is wrong 

### ISSUE THREAD

**Issue by robsoncardosoti** [Alfresco/alfresco-android-app#406]
In Alfresco Mobile with Android configurated to Portuguese language the menu Properties of File is desconfigurated.
In the folder Android/data/org.alfresco.mobile.android.application/files/Conf is copied only embedded_config.json, but with Espanish or English language in Android is copies too en_embedeed_strings.properties.
![screenshot_2016-10-19-21-58-48](https://cloud.githubusercontent.com/assets/18193359/19541771/b2bff3ba-9647-11e6-86ff-d509bd525c1c.png)

**Comment by ruyulin** [comment]
How will they solve this bug?Tell me please, thank you.

**Comment by robsoncardosoti** [comment]
This problem is because the translate files generated in Crowdin not have this menus.
I resolved this problem adding this translate menu in my pt_BR_embedded_strings.properties file.

**Comment by ruyulin** [comment]
Problem has been solved, thank you
