### ISSUE TITLE
Android 4.2.2 crash client

### ISSUE THREAD

**Issue by alejandrosenes** [Alfresco/alfresco-android-app#407]
In android 4.2.2 the client crash when acces to file.
App version 1.7

**Comment by alejandrosenes** [comment]
Alfresco Community v4.2.0
(4576) schema 6022

**Comment by jmpascal** [comment]
Hello,

Sorry to hear you have issue with the App.
Could you be more precise when you say "access to file".
Is it when you try to open it after downloading it (when browsing files) ?
Is it when you go to local Files ?
Does it happen for all types of file? 
Have you send a crash reports and if yes could you tell us when ?

**Comment by jmpascal** [comment]
Without news I will close this issue. Don't hesitate to open a new one or comment on this one.
Thanks.
