### ISSUE TITLE
issue while trying to make custom application 

### ISSUE THREAD

**Issue by ostwalankit** [Alfresco/alfresco-android-app#408]
I am not able to make custom application from alfresco community edition code. I have customised the app look and feel , and it runs fine but as soon as i change package name (Application ID) the app starts misbehaving. 

Getting error like for e.g.

Error during Operation creation : org.alfresco.mobile.android.platform.accounts.DefaultAccountManager

Error during Operation creation : org.alfresco.mobile.android.application.extension.analytics.GAnalyticsManagerImpl

Error during Operation creation : org.alfresco.mobile.android.platform.accounts.DefaultAccountManager

App run absoultely fine while using the original package name 
org.alfresco.mobile.android.application 

but as soon as i alter it , app misbehaves.

I am referring following doc. for custom application.
https://github.com/Alfresco/alfresco-android-app/wiki/Create-Custom-Application

I am stuck on these issue since last 5 days. Help is appreciated.

**Comment by jmpascal** [comment]
Aloah,

Really sorry for the inconvenience. We are aware there's some missing part inside the documentation
We plan to update this section soon. Until that we are happy to provide help if you can provide more information and stacktrace.

**Comment by ostwalankit** [comment]
Hi jmpascal ,I am glad you replied. Thanks for responding. Still could not find a solution.

I worked on alfresco community source code . Modified it according to my requirements. It works all good. But now i want to host this app (apk) on play store, so i am bound to change package name. As soon as i change package name and build apk for release and run , app crashes.

Stacktrace says,

Error during Operation creation : org.alfresco.mobile.android.platform.accounts.DefaultAccountManager

Error during Operation creation : org.alfresco.mobile.android.application.extension.analytics.GAnalyticsManagerImpl

Error during Operation creation : org.alfresco.mobile.android.platform.accounts.DefaultAccountManager

Thank you,

Best Regards,
Ankit.

**Comment by flaviosuardi** [comment]
Hi,
@ostwalankit have you find a solution for this problem? I faced it right now. Did you try to just rename applicationId in gradle and publish the app on google play?
I found there are a lot of reference of `org.alfresco.mobile.android` package in many xml configuration files so it's quite hard to refactor all of these and be able to compile the app.

Thank you.

Flavio

**Comment by ostwalankit** [comment]
Hi @flaviosuardi , no i didn't find any solution to it. If you rename packages , app starts crashing. Let me know if you are able to figure out any solution to this. Thank you..

**Comment by flaviosuardi** [comment]
@shikoko: yes, I renamed that 4 keys but I didn't know if google play could reject the app if package name and application id are different. Furthermore if application id and package name are different, are there any problems with all apps functions?

@ostwalankit The app crash because there are a lot of references of package name in many xml files configuration. One of them if `config_default_managers.xml` in `foundation` module. Anyway if you look the log when the app crashes you can find the name of the unfound class and fix it one by one.

Flavio

**Comment by agologan** [comment]
Closed due to inactivity. Please open a new ticket if problem still persists.
