### ISSUE TITLE
what about jpg upload from Camera 

### ISSUE THREAD

**Issue by amet123** [Alfresco/alfresco-android-app#409]
what about jpg document upload from Camera direct

regards

**Comment by jmpascal** [comment]
Hello,

Could you be more precise on the feature you would like ?
Are you interested by automatically sync photos taken by the camera App to a specific Alfresco Folder ?

Thanks in advance.

**Comment by jmpascal** [comment]
Without news I will close this issue. Don't hesitate to open a new one or comment on this one.
Thanks.
