### ISSUE TITLE
Can't connect to a Alfresco server with self signed certificate.

### ISSUE THREAD

**Issue by Grogdunn** [Alfresco/alfresco-android-app#438]
Hi,
I've tried to create file under /storage/emulated/0/Android/data/org.alfresco.mobile.android.application (empty with <host name>.properties).
But I can't connect to my test server (which has a self signed certificate).
Someone can help me?

Thanks

**Comment by Grogdunn** [comment]
For some reason (I don't know why) the methods described in that guide doesn't work for me.
I've forked the alfresco-android-sdk project and I've modified the PassthruAuthenticationProviderImpl.java for skipping all SSL verification.

**Comment by jmpascal** [comment]
It's indeed the right solution to support this usage. 
We just don't recommend it for obvious reasons in production ^^
