### ISSUE TITLE
Saml Data .class not found in latest client api:1.4.1

### ISSUE THREAD

**Issue by KeyurPatel94** [Alfresco/alfresco-android-app#441]
This below error seems that SAMLDATA class not found in jar file of client API.
I also try some old release version bu not get a solution.

Information:Gradle tasks [:alfresco-mobile-android:assembleCustomDebug]
/home/keyurpatelc2/ALF-ANDROID/alfresco-android-app-master/platform/foundation/src/main/java/org/alfresco/mobile/android/async/session/RequestSessionEvent.java
Error:(21, 62) error: cannot find symbol class SamlData
Error:(30, 18) error: cannot find symbol class SamlData
Error:(58, 63) error: cannot find symbol class SamlData
Error:(68, 63) error: cannot find symbol class SamlData
/home/keyurpatelc2/ALF-ANDROID/alfresco-android-app-master/platform/foundation/src/main/java/org/alfresco/mobile/android/platform/accounts/AlfrescoSessionSettings.java
Error:(24, 62) error: cannot find symbol class SamlData
Error:(42, 18) error: cannot find symbol class SamlData
Error:(89, 52) error: cannot find symbol class SamlData
/home/keyurpatelc2/ALF-ANDROID/alfresco-android-app-master/platform/foundation/src/main/java/org/alfresco/mobile/android/async/account/URLInfo.java
Error:(23, 62) error: cannot find symbol class SamlInfo
Error:(39, 18) error: cannot find symbol class SamlInfo
Error:(41, 93) error: cannot find symbol class SamlInfo
/home/keyurpatelc2/ALF-ANDROID/alfresco-android-app-master/platform/foundation/src/main/java/org/alfresco/mobile/android/async/account/CreateAccountOperation.java
Error:(27, 62) error: cannot find symbol class SamlData
Error:(62, 13) error: cannot find symbol class SamlData
/home/keyurpatelc2/ALF-ANDROID/alfresco-android-app-master/platform/foundation/src/main/java/org/alfresco/mobile/android/async/account/CreateAccountRequest.java
Error:(21, 62) error: cannot find symbol class SamlData
Error:(46, 11) error: cannot find symbol class SamlData
Error:(53, 56) error: cannot find symbol class SamlData
Error:(86, 19) error: cannot find symbol class SamlData
Error:(122, 36) error: cannot find symbol class SamlData
Error:(141, 36) error: cannot find symbol class SamlData
/home/keyurpatelc2/ALF-ANDROID/alfresco-android-app-master/platform/foundation/src/main/java/org/alfresco/mobile/android/async/session/LoadSessionOperation.java
Error:(63, 23) error: reference to LoadSessionHelper is ambiguous
both constructor LoadSessionHelper(Context,AlfrescoAccount,OAuthData) in LoadSessionHelper and constructor LoadSessionHelper(Context,AlfrescoAccount,SamlData) in LoadSessionHelper match
/home/keyurpatelc2/ALF-ANDROID/alfresco-android-app-master/platform/foundation/src/main/java/org/alfresco/mobile/android/async/session/LoadSessionHelper.java
Error:(28, 62) error: cannot find symbol class SamlData
Error:(29, 62) error: cannot find symbol class SamlInfo
Error:(79, 72) error: cannot find symbol class SamlData
Error:(130, 13) error: cannot find symbol class SamlInfo
/home/keyurpatelc2/ALF-ANDROID/alfresco-android-app-master/platform/foundation/src/main/java/org/alfresco/mobile/android/async/account/CheckServerOperation.java
Error:(28, 62) error: cannot find symbol class SamlInfo
Error:(29, 67) error: cannot find symbol class Saml2AuthHelper
Error:(30, 67) error: cannot find symbol class Saml2InfoImpl
Error:(217, 19) error: cannot find symbol class SamlInfo
Error:(181, 17) error: cannot find symbol class Saml2AuthHelper
Error:(181, 46) error: cannot find symbol class Saml2AuthHelper
Error:(188, 21) error: cannot find symbol class Saml2InfoImpl
Error:(188, 46) error: cannot find symbol class Saml2InfoImpl
Error:(222, 13) error: cannot find symbol class Saml2AuthHelper
Error:(222, 42) error: cannot find symbol class Saml2AuthHelper
Error:(229, 28) error: cannot find symbol class Saml2InfoImpl
/home/keyurpatelc2/ALF-ANDROID/alfresco-android-app-master/platform/foundation/src/main/java/org/alfresco/mobile/android/platform/extensions/AnalyticsHelper.java
Error:(30, 62) error: cannot find symbol class SamlAuthenticationProvider
Error:(319, 89) error: cannot find symbol class SamlAuthenticationProvider
/home/keyurpatelc2/ALF-ANDROID/alfresco-android-app-master/platform/foundation/src/main/java/org/alfresco/mobile/android/platform/SessionManager.java
Error:(33, 62) error: cannot find symbol class SamlData
Error:(35, 67) error: cannot find symbol class Saml2TicketImpl
Error:(36, 67) error: cannot find symbol class SamlDataImpl
Error:(300, 74) error: cannot find symbol class SamlData
Error:(315, 68) error: cannot find symbol class SamlData
Error:(339, 19) error: cannot find symbol class SamlData
Error:(395, 56) error: cannot find symbol class SamlData
Error:(465, 36) error: cannot find symbol class SamlDataImpl
Error:(465, 53) error: cannot find symbol class Saml2TicketImpl
Error:Execution failed for task ':platform:foundation:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 1 mins 20.047 secs
Information:46 errors
Information:0 warnings
Information:See complete output in console

**Comment by shikoko** [comment]
Hello,

To solve this issue you should add the SDK v1.5 as the dependency.
