### ISSUE TITLE
Icon Name on android

### ISSUE THREAD

**Issue by Denz86** [Alfresco/alfresco-android-app#442]
Hi,

for the latest alfresco version 1.8 from the google Store, the name of the application Alfresco is "Contenu" (may be only in French...)

It was better when it named "Alfresco", is it an error or a Alfresco's will ? I have to change this name with "Icon Changer Free" for my users. 

Thx

**Comment by john-knowles** [comment]
Closing this since it was opened in 2017, please reopen and comment if you need further assistance.
