### ISSUE TITLE
Sync all an Alfresco Site

### ISSUE THREAD

**Issue by Denz86** [Alfresco/alfresco-android-app#443]
Hi,

If you have sync severals files and folders from different sites we are lost in the "Content synchronsized". We don't know where the files and folders come !

is it difficult to add a synchronization for an entire Alfresco Site ? 
or can you simply put folders with the name of the sites  in the "Content Synchronized" menu ?

Thx a lot

**Comment by shikoko** [comment]
Closing this issue since it was opened in 2017, please reopen and comment if you need further assistance.
