### ISSUE TITLE
Offline files need to load online metadata to open

### ISSUE THREAD

**Issue by dhufnagel** [Alfresco/alfresco-android-app#445]
I have a file synchronized with the app to my phone. If I am not connected to our alfresco server, i cannot open the file offline, because the details page will try to load metadata stored online. This makes offline files useless. The metadata should either be stored offline, or there should be a possibility to open the file without loading the details page.

**Comment by shikoko** [comment]
Closing this issue since it was opened in 2017, please reopen and comment if you need further assistance.
