### ISSUE TITLE
Redirect to application ?

### ISSUE THREAD

**Issue by Denz86** [Alfresco/alfresco-android-app#446]
Hi,
When I send an Afresco URL to an user (like an invitation) who open it with his mobile, it launch Alfresco with the web browser... Severals think they are in the mobile application and all changed ! they are lost...
Is it possible that the Alfresco mobile application detects Alfresco URL to open it in the application at the good place ? (becareful with the mail invitation)
Thanks

(Sorry for my English)

Bonjour,
Quand j'envoie une Alfresco URL à un utilisateur (comme par exemple une invitation Alfresco à rejoindre un site collaboratif), et qu'il clique sur le lien depuis sa tablette, cela va ouvrir le lien dans son navigateur internet et non dans l'application. Du coup, beaucoup croient qu'ils sont dans l'application et que tout à changer ! Ils sont perdus...
Est ce possible que l'application mobile Alfresco detecte une Alfresco URL et l'ouvre dans l'application ? (attention avec les mails d'invitation).
Merci

**Comment by shikoko** [comment]
Closing this issue since it was opened in 2017, please reopen and comment if you need further assistance.
