### ISSUE TITLE
Import Alfresco app in android studio

### ISSUE THREAD

**Issue by GalliaAndre** [Alfresco/alfresco-android-app#448]
Hi, I'm sorry, but I'm trying to open the app and customize it.
I have followed the instructions, but now Android Studio gives me this error:

Error:A problem occurred configuring project ':alfresco-mobile-android'.
> Could not resolve all dependencies for configuration ':alfresco-mobile-android:_mobileironDebugApk'.
   > A problem occurred configuring project ':platform:foundation'.
      > Could not resolve all dependencies for configuration ':platform:foundation:_debugPublishCopy'.
         > Could not find org.alfresco.mobile.android.sdk:alfresco-mobile-android-client-api:1.5.
           Required by:
               alfresco-android-app-1.8.0.platform:foundation:unspecified

Can someone help me, please?
Thanks

**Comment by shikoko** [comment]
Hello,

To solve the issue with the api 1.5 dependency you need to build the [Alfresco Android SDK](https://github.com/Alfresco/alfresco-android-sdk) and install it in your local maven repository as stated here https://github.com/Alfresco/alfresco-android-app/issues/436
