### ISSUE TITLE
Do not support Chinese in the following location

### ISSUE THREAD

**Issue by Jisumix** [Alfresco/alfresco-android-app#449]
I am using Alfresco Android app. I found the following places do not support Chinese. It is not English either. It is the label. 

- In the main navigation panel: home.menu.header
- Detailed information of a file: cm_contentmodel.property.cm_name.title, cm_contentmodel.property_cm_minetype.title and etc. 
- Create new document dialog: creation.mine_type.word.title, creation.mine_type.powerpoint.title, creation.mine_type.excel.title, creation.mine_type.text.title

**Comment by shikoko** [comment]
Hello Jisumix,

We've addressed this issue [here](https://issues.alfresco.com/jira/browse/MOBILE-3410) and also [here](https://issues.alfresco.com/jira/browse/ANDROID-684). The fix will be available in v1.8.5.
