### ISSUE TITLE
Flutter build apk --release ERROR SigningConfig "release" is missing required property "keyPassword"

### ISSUE THREAD

**Issue by ighidan** [Alfresco/alfresco-android-app#548]
I followed the steps for generating a signed APK carefully but when I run the build command it throws an error even though the keyPassword is there.

build.grade:

`signingConfigs{
        release{
            keyAlias 'myapp'
            keyPassword 'xyz@xyz'
            storeFile file('key.jks')
            storePassword 'abc@abc'
        }
    }

buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }`

The error I get is:

`> SigningConfig "release" is missing required property "keyPassword".`

Any idea? Thanks

**Comment by josemiguelo** [comment]
Same error... ;/

**Comment by agologan** [comment]
Code signing section has been added to gradle properties.
Just replace all the vars with your information:
https://github.com/Alfresco/alfresco-android-app/blob/81f3820e42c7a7b0cb3da679c83ceeffb591f53b/gradle.properties#L130

**Comment by santangelx** [comment]
Could you perhaps, at Flutter, notify of these updates ? 
Instead of having developers lose hours and hours of debug ?

**Comment by mohammadzaheri** [comment]
How to fix this error????


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > SigningConfig "release" is missing required property "storeFile".

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by Sumit4482** [comment]
> Code signing section has been added to gradle properties. Just replace all the vars with your information:
> 
> https://github.com/Alfresco/alfresco-android-app/blob/81f3820e42c7a7b0cb3da679c83ceeffb591f53b/gradle.properties#L130

Still getting the same error !!

**Comment by Rod20** [comment]
I had the same error, the solution that worked for me, was to correctly configure the key.properties file, because the "signingConfigs" is based on that configuration, check that it is with the passwords and the exact location of the key with which you signed the app.

**Comment by zeesaan** [comment]
* What went wrong:
Execution failed for task ':app:packageDevRelease'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > SigningConfig "release" is missing required property "storeFile".


How can solved this problem?

**Comment by patelneel9080** [comment]
Still getting same error
