### ISSUE TITLE
Error open project

### ISSUE THREAD

**Issue by jrbrasil** [Alfresco/alfresco-android-app#551]
Hi,
See the error when opening the project:

ERROR: Could not get unknown property 'NEXUS_USERNAME' for root project 'alfresco-android-app' of type org.gradle.api.Project.
Open File

What can it be?
With best regards,
José Roberto
![image (4)](https://user-images.githubusercontent.com/56263837/80012031-10866400-84a3-11ea-81bd-9c631db7cd47.png)

**Comment by jrbrasil** [comment]
Error message

Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'NEXUS_USERNAME' for root project 'alfresco-android-app' of type org.gradle.api.Project.

**Comment by agologan** [comment]
Add missing placeholder vars and did a couple of other changes making it easier to build debug out of the box.
