### ISSUE TITLE
Unable to connect to Alfresco

### ISSUE THREAD

**Issue by gb-123-git** [Alfresco/alfresco-android-app#554]
Hello,

I am unable to connect to Alfresco.

I have already done the following ;

**alfresco-global.properties :**
`opencmis.server.override=true`
`opencmis.server.value=https://<domain.tld>`

**/tomcat/conf/server.xml:**
_Properties added to Connector:_
`<proxyName="<domain.tld>" proxyPort="443" scheme="https" />`

_Properties Added to Engine:_
`<Valve className="org.apache.catalina.valves.RemoteIpValve"
               internalProxies="127\.0\.[0-1]\.1"
               remoteIpHeader="x-forwarded-for"
               requestAttributesEnabled="true"
               protocolHeader="x-forwarded-proto"
               protocolHeaderHttpsValue="https"/>`

I am runnning Tomcat behind Nginx (which is using SSL by LetsEncrypt)

The error I get is : 
_"Your server couldn't be reached._
_Check your account settings."_

Versions:
Alfresco Version: 6.2
App version : 1.8.9.398

One peculiar thing is that if I enter a wrong password, alfresco-log does show 'brute force' attack detected. which means that the app is able to reach the server.

**Comment by agologan** [comment]
We're aware the in-app messages are not explicit enough and may also be misleading pointing to the incorrect issue.

My recommendation is to build a debug version and walk through the request flow.
Alternatively you can hook up a device/emulator to an HTTP proxy like Charles to see the actual requests flowing through (this will require to manually sideload Charles certificate and trust it on your test device).

Lastly if you're not an Android developer,  you may contact Alfresco support or email me directly with the details of the environment you're setting up and we can help you debug the issue.

**Comment by gb-123-git** [comment]
I think the issue was with Share version 6.2.1 and the app has started connecting once the share was upgraded to 6.2.2 (alongwith share services module)
